# 默认使用系统 OpenVINO；需要 TensorRT 时可在配置命令中覆盖：
# cmake -B build -DIMCA_INFERENCE_BACKEND=TENSORRT
set(IMCA_INFERENCE_BACKEND "OPENVINO" CACHE STRING "Inference backend")
set_property(CACHE IMCA_INFERENCE_BACKEND PROPERTY STRINGS OPENVINO TENSORRT)
string(TOUPPER "${IMCA_INFERENCE_BACKEND}" IMCA_INFERENCE_BACKEND)
